server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=dbuser
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

auth.secret=q1w2e3r4t5y6u7i8o9p0zaxscdvfbgnh
auth.issuer=mini-auth
auth.access-ttl-sec=900
auth.refresh-ttl-days=14
auth.clock-skew-sec=60
auth.audience=payments-api

rs.auth-secret=q1w2e3r4t5y6u7i8o9p0zaxscdvfbgnh
rs.auth-server-url=http://localhost:8080
rs.audience=payments-api
rs.clock-skew-sec=60

logging.level.ru.yandex.practicum.oauth0=INFO
